AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resort-api

  Sample SAM Template for resort-api

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'http://localhost:5173'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
  ResortApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: src.app.lambda_handler
      Runtime: python3.14
      FunctionName: resotr-api
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !ImportValue resort-batch-BucketName
          GSI_NAME: !ImportValue resort-batch-GsiName
          TABLE_NAME: !ImportValue resort-batch-TableName
          LAST_UPDATE_PATH: pt_text/last_update.txt
      Architectures:
        - x86_64
      Events:
        GetEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: "/{proxy+}"
            Method: ANY

